### ISSUE TITLE
Automatically serialize Paths to string

### ISSUE THREAD

**Issue by tristanlatr** [NiklasRosenstein/python-databind#14]
Hi, 

I'm running into the following error: `($ ConcreteType(str)): unable to serialize PosixPath -> str`. 

It would be great if `databind` could convert automatically `PathLike` and other `pathlib` or `Traversable` objects to string! 

I assume it's not very hard.

**Comment by NiklasRosenstein** [comment]
databind 1.2.0 has this :)

**Comment by tristanlatr** [comment]
Thanks!
