### ISSUE TITLE
Dependency `typing-extensions<4.7` is too restrictive to install alongside latest Pytorch

### ISSUE THREAD

**Issue by rhaps0dy** [NiklasRosenstein/python-databind#59]
I am trying to figure out dependencies for a project, but `pip-compile` says:

```
ERROR: Cannot install [...]

  The conflict is caused by:
      torch 2.2.1 depends on typing-extensions>=4.8.0
      databind-core 4.4.2 depends on typing-extensions<4.7 and >=3.10.0
```

The restriction to <4.7 is to support Python 3.7, which is no longer supported. Do you want to keep it like that or should I fork? Is there a way to have different dependencies on different python versions?

**Comment by NiklasRosenstein** [comment]
Hi @rhaps0dy 👋 

I think we can throw out Python 3.7 support now. 🙃 I think this will require changes down to typeapi though

**Comment by rhaps0dy** [comment]
I tried bumping their versions to the latest, for Python over 3.7, and the tests worked just fine. Do you think that's proof enough that it works?

**Comment by NiklasRosenstein** [comment]
I would say yes. Thanks for #60!

**Comment by rhaps0dy** [comment]
Thank you for this great piece of software! Looking forward to 4.5.0 😊

**Comment by NiklasRosenstein** [comment]
It's out now. :) Glad you enjoy databind!
