### ISSUE TITLE
[FR] Support `NewType`

### ISSUE THREAD

**Issue by mbway** [NiklasRosenstein/python-databind#70]
I expected that `databind` would treat `NewType` objects the same as the underlying type but instead it crashes with `ClassTypeHint must be initialized from a real type or a generic that points to a real type. Got "__main__.Thing" with origin None`

```python
from dataclasses import dataclass
from typing import NewType
from databind.json import load

Thing = NewType("Thing", str)
# Thing = str  # this works

@dataclass
class MyClass:
    foo: Thing

print(load({"foo": "bar"}, MyClass))
```
looks like the issue is that `NewType` is a class so `Thing` is technically an object and not a type. Maybe `NewType` support requires special handling?

One (pretty bad) workaround is to use `TYPE_CHECKING`:
```python
@dataclass
class MyClass:
    if TYPE_CHECKING:
        foo: Thing
    else:
        foo: Thing.__supertype__
```
this class can be used with databind but is type checked as `foo: Thing` afterwards

**Comment by NiklasRosenstein** [comment]
Hi @mbway , thanks for raising this issue.

This change to `typeapi` should fix it: https://github.com/NiklasRosenstein/python-typeapi/pull/38

**Comment by NiklasRosenstein** [comment]
`typeapi 2.2.2` has this change!
